
function init(obj)
	local new_binder = anomaly_binder(obj)
	obj:bind_object(new_binder)
end


local mine_zones = {}
class "anomaly_binder" (object_binder)
function anomaly_binder:__init(obj) super(obj)
	self.saved_obj = {}
	mine_zones[obj:name()] = self
end 

function anomaly_binder:reload(section)
object_binder.reload(self, section)
end

function anomaly_binder:reinit()
object_binder.reinit(self)
--	self.object:set_callback(callback.on_hit, self.on_anomaly_hit, self)		-- хит аномалией объекта
end

function anomaly_binder:net_save_relevant()
	return true
end

function anomaly_binder:save(packet)

	object_binder.save(self, packet)
	
	local num = table.getn(self.saved_obj)
	packet:w_u8(num)
	for k,v in pairs(self.saved_obj) do
		packet:w_u16(k)
	end
end

function anomaly_binder:load(packet)
	object_binder.load(self, packet)

	local num = packet:r_u8()	
	for i=1,num do
		self.saved_obj[packet:r_u16()] = true
	end	
end

function anomaly_binder:net_spawn(data)
    if not object_binder.net_spawn(self, data) then
        return false
    end
	self.object:set_callback(callback.zone_enter, self.on_enter, self)
	self.object:set_callback(callback.zone_exit, self.on_exit, self)
    return true
end



function anomaly_binder:on_exit(zone, obj)
--	if obj:clsid() == clsid.actor or obj:section() == "a_inventory_box52" then
--		return
--	end

	printf("[zone %s] on_enter obj=%s, clsid=%s", zone:name(), obj:name(), obj:clsid())
	self.saved_obj[obj:id()] = nil
end


function anomaly_binder:update()
object_binder.update(self, delta)
end

function anomaly_binder:net_destroy()
	self.object:set_callback(callback.zone_enter, nil)
	self.object:set_callback(callback.zone_exit, nil)
    object_binder.net_destroy(self)
end

function anomaly_binder:on_enter(zone, obj)
	printf("[zone %s] on_enter obj=%s, clsid=%s", zone:name(), obj:name(), obj:clsid())
	local anom = self.object:section()
	local state_anom = self.object:id()
	if anom == "zone_mine_field" then
		local del_anom = self.object:id()
		 amk.start_timer("mina", 2, del_anom)
	end
	self.saved_obj[obj:id()] = true
end

function anomaly_binder:on_anomaly_hit(gameobj)
if not gameobj:is_artefact() then
	local a = gameobj:name()
	local anom = self.object:section()

	------------- мины ----------------------------
	if anom == "zone_mine_field" then
--log1("Найдена мина")
		local del_anom = self.object:id()
		my.start_timer("mina", 2, del_anom)
	end

		------------- Комариная плешь ----------------------------
	if string.sub(anom,1,18) =="zone_mosquito_bald" then
--		if anom == "zone_mosquito_bald_weak_noart" or anom == "zone_mosquito_bald_strong_noart" then return end
		local rarets = 10
		if gameobj:is_monster() or gameobj:is_stalker() then
			if gameobj:alive() == false then
			local pos = gameobj:position()
			local radius = 15
			local dist = pos:distance_to(self.object:position())
				if dist < radius then

					local art = {"af_medusa", "af_cristall_flower","af_night_star"}
					local number = math.ceil(math.random(1, 3))
					local rrr = math.ceil(math.random(0, 100))
--log1("zone_mosquito_bald ".. rrr)
						if rrr < rarets then
							local snd_obj = xr_sound.get_safe_sound_object([[anomaly\gravity_entrance]])
							snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
							--local particle = "1935\\group_items\\expl_mushroom_glow00"
						        --	if particle ~= nil then
					            	--		particle = particles_object(particle)
					        	--    		particle:play_at_pos(db.actor:position())
						        --	end
							alife():create(art[number],	
							self.object:position(),
							self.object:level_vertex_id(),	
							self.object:game_vertex_id())
					local se_obj = alife():object(a)
					local sobjid = gameobj:id()
						if se_obj then
							gameobj:kill(gameobj)
							anomaly_nah(sobjid)
--							alife():release(se_obj, true)
						end
						end
				end
			end

		else
		end

		----------------- Электра ---------------------

	elseif string.sub(anom,1,22) =="zone_witches_galantine" then
		local rarets = 20
		if gameobj:is_monster() or gameobj:is_stalker() then
			if gameobj:alive() and gameobj.health < 0.2 then
			local pos = gameobj:position()
			local radius = 15
			local dist = pos:distance_to(self.object:position())
				if dist < radius then
					local art = {"af_electra_sparkler", "af_electra_flash", "af_electra_moonlight"}
					local number = math.ceil(math.random(1, 3))
					local rrr = math.ceil(math.random(0, 100))
						if rrr < rarets then
							local snd_obj = xr_sound.get_safe_sound_object([[anomaly\gravity_entrance]])
							snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
							local particle = "anomaly2\\emi_entrance_big_00"
						        	if particle ~= nil then
					            			particle = particles_object(particle)
					        	    		particle:play_at_pos(db.actor:position())
						        	end
							alife():create(art[number],	
							pos,
							self.object:level_vertex_id(),	
							self.object:game_vertex_id())
					local se_obj = alife():object(a)
					local sobjid = gameobj:id()
						if se_obj then
							gameobj:kill(gameobj)
							anomaly_nah(sobjid)
--							alife():release(se_obj, true)
						end

						end
				end
			end

		else
		end

		------------- Мясорубка ----------------------------
	elseif string.sub(anom,1,11) =="zone_mincer" then
		local popal = gameobj:section()  or "zatychka"
		if popal and string.sub(popal,1,18) =="ph_skeleton_object" then
		   if gameobj then
			local bone = gameobj:get_bone_name() or "zatychka1"

			if bone and string.sub(bone,1,4) =="head" or string.sub(bone,1,4) =="root" then
				local pos = gameobj:position()
				local radius = 7
				local dist = pos:distance_to(self.object:position())
					if dist < radius then
						local rarets = 10
			local art = {"af_blood", "af_mincer_meat","af_soul"}
						local number = math.ceil(math.random(1, 4))
						local rrr = math.ceil(math.random(0, 100))
					   if rrr < rarets then
						local se_obj = alife():object(a)
							if se_obj then
								alife():release(se_obj, true)
							end
						local snd_obj = xr_sound.get_safe_sound_object([[anomaly\gravity_entrance]])
						snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
						--local particle = "1935\\group_items\\expl_mushroom_glow00"
			       			--	if particle ~= nil then
			 			--		particle = particles_object(particle)
			   			--		particle:play_at_pos(db.actor:position())
			       			--	end
						local posan = self.object:position()
 						local off = math.random(1, 10)
						posan.x = pos.x + off
						posan.y = pos.y + off
						posan.z = pos.z + off
						alife():create(art[number],	
						posan,
						self.object:level_vertex_id(),	
						self.object:game_vertex_id())
					  end
		  			end
			end
		   end
		else
		end


		------------- Воронка  ----------------------------
	elseif string.sub(anom,1,15) =="zone_gravi_zone" then
--		if anom == "zone_gravi_zone_noart" then return end
		local rarets = 10
		if gameobj:is_monster() or gameobj:is_stalker() then
			if gameobj:alive() == false then
			local pos = gameobj:position()
			local radius = 15
			local dist = pos:distance_to(self.object:position())
				if dist < radius then
					local art = {"af_vyvert", "af_gravi","af_gold_fish"}
					local number = math.ceil(math.random(1, 3))
					local rrr = math.ceil(math.random(0, 100))
--log1("zone_gravi_zone "..rrr)
						if rrr < rarets then
							local snd_obj = xr_sound.get_safe_sound_object([[anomaly\gravity_entrance]])
							snd_obj:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
							--local particle = "1935\\group_items\\expl_mushroom_glow00"
						        --	if particle ~= nil then
					            	--		particle = particles_object(particle)
					        	--    		particle:play_at_pos(db.actor:position())
						        --	end
							alife():create(art[number],	
							self.object:position(),
							self.object:level_vertex_id(),	
							self.object:game_vertex_id())
				end
			end
			end
		else
		end
	end
end
end

function anomaly_nah(object_id)
	local new_pos = vector():set(-143.19,-500.22,653.37)
	local new_lvid = 56131
	local new_gvid = 2596
alife():teleport_object(object_id, new_pos, new_lvid, new_gvid)
end
