function allow_break_dialog(first_speaker, second_speaker, id)
	if second_speaker:profile_name() == "osoznanie" then
		return false
	end
	return true
end


function break_dialog(first_speaker, second_speaker, id)
	first_speaker:stop_talk()
	second_speaker:stop_talk()
end

function disable_talk_self(first_speaker, second_speaker)
	first_speaker:disable_talk()
end
function disable_talk_victim(first_speaker, second_speaker)
	second_speaker:disable_talk()
end

function punch(first_speaker, second_speaker)
	--abort("KICK ASS !!!!")
	--xr_punch.punch[first_speaker:id()] = second_speaker
	db.storage[second_speaker:id()].punch.enabled = true
end

function get_money_then_leave(first_speaker, second_speaker)
	db.storage[first_speaker:id()].meet.enabled = false
	db.storage[first_speaker:id()].robber.enabled = true
end

function is_wounded(first_speaker, second_speaker)
    if db.storage[first_speaker:id()].wounded ~= nil and
       db.storage[first_speaker:id()].wounded.wound_manager.can_use_medkit == true
    then
        return false
    end

	return xr_wounded.is_wounded(first_speaker)
end
function is_opp_wounded(first_speaker, second_speaker, dialog_id)
    if db.storage[second_speaker:id()].wounded ~= nil and
       db.storage[second_speaker:id()].wounded.wound_manager.can_use_medkit == true
    then
        return false
    end
	return	xr_wounded.is_wounded(second_speaker)
end
function is_not_wounded(first_speaker, second_speaker)
	return not this.is_wounded(first_speaker, second_speaker)
end
function actor_have_medkit(first_speaker, second_speaker)
	return first_speaker:object("medkit") ~= nil or
		   first_speaker:object("medkit_army") ~= nil or
		   first_speaker:object("medkit_scientic") ~= nil
end
function actor_have_bandage(first_speaker, second_speaker)
	return first_speaker:object("bandage") ~= nil
end
function transfer_medkit(first_speaker, second_speaker)
	if first_speaker:object("medkit") ~= nil then
		dialogs.relocate_item_section(second_speaker, "medkit", "out")
	elseif first_speaker:object("medkit_army") ~= nil then
		dialogs.relocate_item_section(second_speaker, "medkit_army", "out")
	else
		dialogs.relocate_item_section(second_speaker, "medkit_scientic", "out")
	end

	--' Тут надо анлочить аптечку для использования.
	xr_wounded.unlock_medkit(second_speaker)
		
	if second_speaker:relation(first_speaker) ~= game_object.enemy then
		second_speaker:set_relation(game_object.friend, first_speaker)
	end
	first_speaker:change_character_reputation(10);
end
function transfer_bandage(first_speaker, second_speaker)
	dialogs.relocate_item_section(second_speaker, "bandage", "out")
	second_speaker:set_relation(game_object.friend, first_speaker)
end
function kill_yourself(npc, actor)
	npc:kill(actor)
end
function make_suicide(npc, actor)
	actor:kill(npc)
end

function actor_dead(actor)
	local actor = db.actor
	actor:kill(actor)
end


--' Obsolete, do not use!!!
function relocate_item(victim, obj, type)
	if db.actor and victim then
		if type == "in" then
			victim:transfer_item(obj, db.actor)
		elseif type == "out" then
			db.actor:transfer_item(obj, victim)
		end
		--'news_manager.relocate_item(db.actor, type, obj)
	end
end
--' Use this function instead.
function relocate_item_section(victim, section, type)
	if db.actor and victim then
		if type == "in" then

			--' Трансферить нужно только квестовые предметы.
			if quest_section[section] == true and
			   victim:object(section) ~= nil 
			then
				victim:transfer_item(victim:object(section), db.actor)
			else
				alife():create(section,	
					    db.actor:position(),
						db.actor:level_vertex_id(),	
						db.actor:game_vertex_id(),
						db.actor:id())
			end
		elseif type == "out" then
			db.actor:transfer_item(db.actor:object(section), victim)
		end
		news_manager.relocate_item(db.actor, type, section)
	end
end


function relocate_money(victim, num, type)
	if db.actor and victim then
		if type == "in" then
			db.actor:give_money(num)
			game_stats.money_quest_update (num) 
		elseif type == "out" then
			db.actor:transfer_money(num, victim)
			game_stats.money_quest_update (-num) 
		end
		news_manager.relocate_money(db.actor, type, num)
	end
end

--'---------------------------------------------------------------------------------
--' DIALOG ALLOWED
--'---------------------------------------------------------------------------------
function dialog_allowed(object, victim, id)
	if id ~= nil then
--		printf("*DIALOGS*: dialog_allowed: %s", id)
	else
--		printf("*DIALOGS*: dialog_allowed: nil")
	end
	if db.storage[victim:id()].actor_dialogs ~= nil then
		for k,v in pairs(db.storage[victim:id()].actor_dialogs) do
			if v == id then return true end
		end
	end
	return false
end
function dialog_not_disable(object, victim, id)
	if id ~= nil then
--		printf("*DIALOGS*: dialog_disable:%s", id)
	else
--		printf("*DIALOGS*: dialog_disable:nil")
	end
	if db.storage[victim:id()].actor_disable ~= nil then
		for k,v in pairs(db.storage[victim:id()].actor_disable) do
			if v == id then return false end
		end
	end
	return true
end

function allow_wounded_dialog(object, victim, id)
	if db.storage[victim:id()].wounded == nil then
		return false
	end	
	if db.storage[victim:id()].wounded.help_dialog == id then
		return true
	end
	return false	
end


-----------------------------------------------------------------------------------
-- LEVELS
-----------------------------------------------------------------------------------
function level_escape(first_speaker, second_speaker)
	return level.name() == "l01_escape"
end

function level_garbage(first_speaker, second_speaker)
	return level.name() == "l02_garbage"
end

function level_agroprom(first_speaker, second_speaker)
	return level.name() == "l03_agroprom_ai2" or level.name() == "l03_agroprom"
end

-----------------------------------------------------------------------------------
-- Relation functions
-----------------------------------------------------------------------------------
function is_friend(first_speaker, second_speaker)
	return first_speaker:relation(second_speaker) == game_object.friend
end

function is_not_friend(first_speaker, second_speaker)
	return not is_friend(first_speaker, second_speaker)
end

function become_friend(first_speaker, second_speaker)
	first_speaker:set_relation(game_object.friend, second_speaker)
end

function become_friend_meet(first_speaker, second_speaker)
	second_speaker:set_relation(game_object.friend, first_speaker)
end

-----------------------------------------------------------------------------------
-- Community
-----------------------------------------------------------------------------------
function actor_in_dolg(actor, npc)
	if db.actor then
		return db.actor:character_community() == "actor_dolg"
	end
	return false
end
function actor_not_in_dolg(actor, npc)
	return not actor_in_dolg(actor, npc)
end
function actor_set_dolg(actor, npc)
	printf("ACTOR NOW IN [DOLG] COMMUNITY")
	if db.actor then
		db.actor:set_character_community("actor_dolg", 0, 0)
	end
	return true
end
function actor_clear_community(actor, npc)
	printf("ACTOR NOW IN [NEUTRAL] COMMUNITY")
	if db.actor then
		db.actor:set_character_community("actor", 0, 0)
	end
	return true
end

-----------------------------------------------------------------------------------
-- Money functions
-----------------------------------------------------------------------------------
function has_2000_money(first_speaker, second_speaker)
	return first_speaker:money() >= 2000
end

function has_5000_money(first_speaker, second_speaker)
	return first_speaker:money() >= 5000
end

-----------------------------------------------------------------------------------
-- Item functions
-----------------------------------------------------------------------------------
function has_xform_1(first_speaker, second_speaker)
	return first_speaker:object("xform_1") ~= nil
end

function has_docum_case(second_speaker, first_speaker)
	return first_speaker:object("docum_case") ~= nil
end

function hasnot_docum_case(second_speaker, first_speaker)
	return first_speaker:object("docum_case") == nil
end

function has_dolg_jeton(first_speaker, second_speaker)
	return first_speaker:object("free_repair_jeton") ~= nil
end

function hasnot_dolg_jeton(first_speaker, second_speaker)
	return first_speaker:object("free_repair_jeton") == nil
end

function has_m1000(first_speaker, second_speaker)
	return second_speaker:object("wpn_m1000") ~= nil
end

function hasnot_m1000(first_speaker, second_speaker)
	return second_speaker:object("wpn_m1000") == nil
end

function has_steppan_letter(first_speaker, second_speaker)
	return first_speaker:object("ss_document_12") ~= nil
end

function has_full_complect(first_speaker, second_speaker)
	return	first_speaker:object("af_electra_moonlight_zombie") ~= nil and
			first_speaker:object("af_medusa_zombie") ~= nil and
			first_speaker:object("af_cristall_flower_zombie") ~= nil and
			first_speaker:object("af_night_star_zombie") ~= nil and
			first_speaker:object("af_vyvert_zombie") ~= nil and
			first_speaker:object("af_gravi_zombie") ~= nil and
			first_speaker:object("af_gold_fish_zombie") ~= nil and
			first_speaker:object("af_drops_zombie") ~= nil and
			first_speaker:object("af_fireball_zombie") ~= nil and
			first_speaker:object("af_cristall_zombie") ~= nil and
			first_speaker:object("af_blood_zombie") ~= nil and
			first_speaker:object("af_mincer_meat_zombie") ~= nil and
			first_speaker:object("af_soul_zombie") ~= nil and
			first_speaker:object("af_electra_sparkler_zombie") ~= nil and
			first_speaker:object("af_electra_flash_zombie") ~= nil and
			first_speaker:object("af_ameba_slime_zombie") ~= nil and
			first_speaker:object("af_ameba_slug_zombie") ~= nil and
			first_speaker:object("af_ameba_mica_zombie") ~= nil and
			first_speaker:object("af_dummy_spring_zombie") ~= nil and
			first_speaker:object("af_dummy_dummy_zombie") ~= nil and
			first_speaker:object("af_dummy_battery_zombie") ~= nil and
			first_speaker:object("af_dummy_pellicle_zombie") ~= nil and
			first_speaker:object("af_dummy_glassbeads_zombie") ~= nil and
			first_speaker:object("af_rusty_thorn_zombie") ~= nil and
			first_speaker:object("af_rusty_kristall_zombie") ~= nil and
			first_speaker:object("af_rusty_sea_urchin_zombie") ~= nil and
			first_speaker:object("af_fuzz_kolobok_zombie") ~= nil
end

function has_w_pri_sniper_pda(first_speaker, second_speaker)
	return first_speaker:object("sniper_pda") ~= nil
end

function has_crucian_pda(first_speaker, second_speaker)
	return first_speaker:object("crucian_pda") ~= nil
end

function has_pope_letter(second_speaker, first_speaker)
	return first_speaker:object("malyawa_07") ~= nil
end



-- Арты
function jj_has_af_medusa(first_speaker, second_speaker)
	return first_speaker:object("af_medusa") ~= nil
end

function jj_has_af_cristall_flower(first_speaker, second_speaker)
	return first_speaker:object("af_cristall_flower") ~= nil
end

function jj_has_af_night_star(first_speaker, second_speaker)
	return first_speaker:object("af_night_star") ~= nil
end

function jj_has_af_vyvert(first_speaker, second_speaker)
	return first_speaker:object("af_vyvert") ~= nil
end

function jj_has_af_gravi(first_speaker, second_speaker)
	return first_speaker:object("af_gravi") ~= nil
end

function jj_has_af_gold_fish(first_speaker, second_speaker)
	return first_speaker:object("af_gold_fish") ~= nil
end

function jj_has_af_drops(first_speaker, second_speaker)
	return first_speaker:object("af_drops") ~= nil
end

function jj_has_af_fireball(first_speaker, second_speaker)
	return first_speaker:object("af_fireball") ~= nil
end

function jj_has_af_cristall(first_speaker, second_speaker)
	return first_speaker:object("af_cristall") ~= nil
end

function jj_has_af_blood(first_speaker, second_speaker)
	return first_speaker:object("af_blood") ~= nil
end

function jj_has_af_mincer_meat(first_speaker, second_speaker)
	return first_speaker:object("af_mincer_meat") ~= nil
end

function jj_has_af_soul(first_speaker, second_speaker)
	return first_speaker:object("af_soul") ~= nil
end

function jj_has_af_electra_sparkler(first_speaker, second_speaker)
	return first_speaker:object("af_electra_sparkler") ~= nil
end

function jj_has_af_electra_flash(first_speaker, second_speaker)
	return first_speaker:object("af_electra_flash") ~= nil
end

function jj_has_af_electra_moonlight(first_speaker, second_speaker)
	return first_speaker:object("af_electra_moonlight") ~= nil
end

function jj_has_af_ameba_slime(first_speaker, second_speaker)
	return first_speaker:object("af_ameba_slime") ~= nil
end

function jj_has_af_ameba_slug(first_speaker, second_speaker)
	return first_speaker:object("af_ameba_slug") ~= nil
end

function jj_has_af_ameba_mica(first_speaker, second_speaker)
	return first_speaker:object("af_ameba_mica") ~= nil
end

function jj_has_af_dummy_spring(first_speaker, second_speaker)
	return first_speaker:object("af_dummy_spring") ~= nil
end

function jj_has_af_dummy_dummy(first_speaker, second_speaker)
	return first_speaker:object("af_dummy_dummy") ~= nil
end

function jj_has_af_dummy_battery(first_speaker, second_speaker)
	return first_speaker:object("af_dummy_battery") ~= nil
end

function jj_has_af_dummy_pellicle(first_speaker, second_speaker)
	return first_speaker:object("af_dummy_pellicle") ~= nil
end

function jj_has_af_dummy_glassbeads(first_speaker, second_speaker)
	return first_speaker:object("af_dummy_glassbeads") ~= nil
end

function jj_has_af_rusty_thorn(first_speaker, second_speaker)
	return first_speaker:object("af_rusty_thorn") ~= nil
end

function jj_has_af_rusty_kristall(first_speaker, second_speaker)
	return first_speaker:object("af_rusty_kristall") ~= nil
end

function jj_has_af_rusty_sea_urchin(first_speaker, second_speaker)
	return first_speaker:object("af_rusty_sea-urchin") ~= nil
end

function jj_has_af_fuzz_kolobok(first_speaker, second_speaker)
	return first_speaker:object("af_fuzz_kolobok") ~= nil
end

function jj_has_concord(first_speaker, second_speaker)
	return first_speaker:object("concord") ~= nil
end

function jj_has_black_soul(first_speaker, second_speaker)
	return first_speaker:object("black_soul") ~= nil
end

function jj_has_glowworm(first_speaker, second_speaker)
	return first_speaker:object("glowworm") ~= nil
end

function jj_has_af_doping(first_speaker, second_speaker)
	return first_speaker:object("af_doping") ~= nil
end

--[[function has_(first_speaker, second_speaker)
	return first_speaker:object("") ~= nil
end]]

--[[function hasnot_(first_speaker, second_speaker)
	return second_speaker:object("") == nil
end]]

-----------------------------------------------------------------------------------
-- TRADE
-----------------------------------------------------------------------------------
--' Инициализация торговли
function trade_init(seller, buyer)
	db.storage[seller:id()].meet.begin_wait_to_see.begin = time_global()/1000
	xr_position.setPosition(db.storage[seller:id()].meet.Seller, 
							db.storage[seller:id()].meet.Seller:level_vertex_id())
	db.storage[seller:id()].meet.Buyer = buyer
end

function want_trade(seller, buyer)
	if seller:relation(buyer) == game_object.friend or
		seller:relation(buyer) == game_object.neutral
	then
		return true
	else
		return false
	end
end

function dont_want_trade(seller, buyer)	
	return not want_trade(seller,buyer)
end

-----------------------------------------------------------------
------------ DFS
-----------------------------------------------------------------
function moldovan_enabled(npc, actor)
if	db.actor:has_info("zaglushka_4") or
	db.actor:has_info("zaglushka_6") then
return true 
	end 
end

function actor_have_items_1(first_speaker, second_speaker)
	return first_speaker:object("wpn_p38_sk1") ~= nil and
		   first_speaker:object("ss_document_01") ~= nil and
		   first_speaker:object("ss_document_02") ~= nil and
		   first_speaker:object("ss_document_03") ~= nil
end

function sper_kalash(second_speaker, first_speaker)
	return first_speaker:object("wpn_ak74_m1") ~= nil
end

function ne_sper_kalash(second_speaker, first_speaker)
	return first_speaker:object("wpn_ak74_m1") == nil
end

function actor_has_pass(first_speaker, second_speaker)
	return first_speaker:object("passdoc") ~= nil
end

function actor_hasnot_pass(first_speaker, second_speaker)
	return first_speaker:object("passdoc") == nil
end

function has_vodka(first_speaker, second_speaker)
	return first_speaker:object("vodka") ~= nil
end

function degenerates_kba(actor, npc)
	if	db.actor:has_info("yo_bastard_01_kba") and
		db.actor:has_info("yo_bastard_02_kba") and
		db.actor:has_info("yo_bastard_03_kba") and
		db.actor:has_info("yo_bastard_04_kba") and
		db.actor:has_info("yo_bastard_05_kba") and
		db.actor:has_info("yo_bastard_06_kba") then
	return true
	end
	return false
end

function degenerates_nkba(actor, npc)
	if	db.actor:dont_has_info("yo_bastard_01_kba") or
		db.actor:dont_has_info("yo_bastard_02_kba") or
		db.actor:dont_has_info("yo_bastard_03_kba") or
		db.actor:dont_has_info("yo_bastard_04_kba") or
		db.actor:dont_has_info("yo_bastard_05_kba") or
		db.actor:dont_has_info("yo_bastard_06_kba") then
	return true
	end
	return false
end

function has_p38(first_speaker, second_speaker)
	return first_speaker:object("wpn_p38_sk1") ~= nil
end

function dont_has_p38(first_speaker, second_speaker)
	return first_speaker:object("wpn_p38_sk1") == nil
end

function has_scaner(first_speaker, second_speaker)
	return first_speaker:object("radio_scaner") ~= nil
end

function dont_has_scaner(first_speaker, second_speaker)
	return first_speaker:object("radio_scaner") == nil
end

function has_c4(first_speaker, second_speaker)
	return first_speaker:object("explosive_c4") ~= nil
end

function w_pri_is_night(actor, npc)
	--return level.get_time_hours() < 6 and level.get_time_hours() >= 21
	return not xr_conditions.is_day()
end

function actor_have_items_2(first_speaker, second_speaker)
	return first_speaker:object("berkov_code_tables") ~= nil and
		   first_speaker:object("ss_document_13") ~= nil
end

function yakowlew_is_not_wounded(first_speaker, second_speaker)
	return not this.is_wounded(second_speaker)
end




