function take_items(obj)
if obj:section() == "wpn_pm" then
pistol_take_sound()
end

--
-- 03.04.2026
--

if obj:section() == "af_doping" then
detectors_take_sound()
end
if obj:section() == "af_antidoping" then
detectors_take_sound()
end
if obj:section() == "glowworm" then
detectors_take_sound()
end
if obj:section() == "black_soul" then
detectors_take_sound()
end
if obj:section() == "concord" then
detectors_take_sound()
end

--
-- 03.04.2026
--

if obj:section() == "wpn_pm_arena" then
pistol_take_sound()
end
if obj:section() == "wpn_pb" then
pistol_take_sound()
end
if obj:section() == "wpn_aps" then
pistol_take_sound()
end
if obj:section() == "wpn_beretta" then
pistol_take_sound()
end
if obj:section() == "wpn_beretta_m1" then
pistol_take_sound()
end
if obj:section() == "wpn_colt1911" then
pistol_take_sound()
end
if obj:section() == "wpn_colt_m1" then
pistol_take_sound()
end
if obj:section() == "wpn_deset_eagle" then
pistol_take_sound()
end
if obj:section() == "wpn_eagle_m1" then
pistol_take_sound()
end
if obj:section() == "wpn_deserteagle_coll" then
pistol_take_sound()
end
if obj:section() == "wpn_fort" then
pistol_take_sound()
end
if obj:section() == "wpn_fort_m1" then
pistol_take_sound()
end
if obj:section() == "wpn_gsh18" then
pistol_take_sound()
end
if obj:section() == "wpn_hk53" then
pistol_take_sound()
end
if obj:section() == "wpn_hpsa" then
pistol_take_sound()
end
if obj:section() == "wpn_klin" then
pistol_take_sound()
end
if obj:section() == "wpn_kriss_super_v" then
pistol_take_sound()
end
if obj:section() == "wpn_mac10" then
pistol_take_sound()
end
if obj:section() == "wpn_ots33" then
pistol_take_sound()
end
if obj:section() == "wpn_mp5" then
pistol_take_sound()
end
if obj:section() == "wpn_mp5_m1" then
pistol_take_sound()
end
if obj:section() == "wpn_mp5_m2" then
pistol_take_sound()
end
if obj:section() == "wpn_mp5_arena" then
pistol_take_sound()
end
if obj:section() == "wpn_p90" then
pistol_take_sound()
end
if obj:section() == "wpn_scorpion" then
pistol_take_sound()
end
if obj:section() == "wpn_sig220" then
pistol_take_sound()
end
if obj:section() == "wpn_tec9" then
pistol_take_sound()
end
if obj:section() == "wpn_usp" then
pistol_take_sound()
end
if obj:section() == "wpn_walther" then
pistol_take_sound()
end
if obj:section() == "wpn_walther_m1" then
pistol_take_sound()
end
if obj:section() == "wpn_walther_coll" then
pistol_take_sound()
end
if obj:section() == "wpn_abakan" then
rifle_take_sound()
end
if obj:section() == "pri_lom_ak74" then
rifle_take_sound()
end
if obj:section() == "wpn_abakan_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_abakan_m2" then
rifle_take_sound()
end
if obj:section() == "wpn_abakan_m3" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74u" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74u_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74u_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_ak74u_anom" then
rifle_take_sound()
end
if obj:section() == "wpn_akm74" then
rifle_take_sound()
end
if obj:section() == "wpn_akmc" then
rifle_take_sound()
end
if obj:section() == "wpn_aks74" then
rifle_take_sound()
end
if obj:section() == "wpn_benelli_short" then
rifle_take_sound()
end
if obj:section() == "wpn_bizon" then
rifle_take_sound()
end
if obj:section() == "wpn_bm16" then
rifle_take_sound()
end
if obj:section() == "wpn_bm16_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_bm16_full" then
rifle_take_sound()
end
if obj:section() == "wpn_fn2000" then
rifle_take_sound()
end
if obj:section() == "wpn_fn2000_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_g36" then
rifle_take_sound()
end
if obj:section() == "wpn_g36_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_g36_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_gauss" then
rifle_take_sound()
end
if obj:section() == "wpn_gm94" then
rifle_take_sound()
end
if obj:section() == "wpn_groza" then
rifle_take_sound()
end
if obj:section() == "wpn_groza_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_groza_m2" then
rifle_take_sound()
end
if obj:section() == "wpn_groza_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_groza_old" then
rifle_take_sound()
end
if obj:section() == "wpn_l85" then
rifle_take_sound()
end
if obj:section() == "wpn_l85_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_l85_m2" then
rifle_take_sound()
end
if obj:section() == "wpn_l85_m3" then
rifle_take_sound()
end
if obj:section() == "wpn_lr300" then
rifle_take_sound()
end
if obj:section() == "wpn_lr300_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_m1891_30" then
rifle_take_sound()
end
if obj:section() == "wpn_protecta" then
rifle_take_sound()
end
if obj:section() == "wpn_rpk74" then
rifle_take_sound()
end
if obj:section() == "wpn_saiga12c" then
rifle_take_sound()
end
if obj:section() == "wpn_shotgra" then
rifle_take_sound()
end
if obj:section() == "wpn_sig550" then
rifle_take_sound()
end
if obj:section() == "wpn_sig_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_sig_m2" then
rifle_take_sound()
end
if obj:section() == "wpn_sig_m3" then
rifle_take_sound()
end
if obj:section() == "wpn_spas12" then
rifle_take_sound()
end
if obj:section() == "wpn_spas12_arena" then
rifle_take_sound()
end
if obj:section() == "wpn_spas12_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_svd" then
rifle_take_sound()
end
if obj:section() == "wpn_svd_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_svu" then
rifle_take_sound()
end
if obj:section() == "wpn_svu_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_svu_m2" then
rifle_take_sound()
end
if obj:section() == "wpn_toz34" then
rifle_take_sound()
end
if obj:section() == "hunters_toz" then
rifle_take_sound()
end
if obj:section() == "wpn_val" then
rifle_take_sound()
end
if obj:section() == "wpn_val_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_vintorez" then
rifle_take_sound()
end
if obj:section() == "wpn_vintorez_coll" then
rifle_take_sound()
end
if obj:section() == "wpn_vsk94" then
rifle_take_sound()
end
if obj:section() == "wpn_wincheaster1300" then
rifle_take_sound()
end
if obj:section() == "wpn_winchester_m1" then
rifle_take_sound()
end
if obj:section() == "wpn_knife" then
knife_take_sound()
end
if obj:section() == "fake_wpn_knife" then
knife_take_sound()
end
if obj:section() == "wpn_knife_d" then
knife_take_sound()
end
if obj:section() == "fake_wpn_knife_d" then
knife_take_sound()
end
if obj:section() == "vodka" then
bottle_take_sound()
end
if obj:section() == "vodka_a" then
bottle_take_sound()
end
if obj:section() == "ammo_9x18_fmj" then
pistol_ammo_take_sound()
end
if obj:section() == "ammo_9x18_pmm" then
pistol_ammo_take_sound()
end
if obj:section() == "ammo_9x18_pbp" then
pistol_ammo_take_sound()
end
if obj:section() == "ammo_9x19_fmj" then
pistol_ammo_take_sound()
end
if obj:section() == "ammo_9x19_pbp" then
pistol_ammo_take_sound()
end
if obj:section() == "ammo_11.43x23_fmj" then
pistol_ammo_take_sound()
end
if obj:section() == "ammo_11.43x23_hydro" then
pistol_ammo_take_sound()
end
if obj:section() == "grenade_gd-05" then
grenade_take_sound()
end
if obj:section() == "grenade_rgd5" then
grenade_take_sound()
end
if obj:section() == "grenade_f1" then
grenade_take_sound()
end
if obj:section() == "grenade_flashbang_zaria" then
grenade_take_sound()
end
if obj:section() == "grenade_rgo" then
grenade_take_sound()
end
if obj:section() == "ammo_og-7b" then
grenade_ammo_take_sound()
end
if obj:section() == "ammo_igla" then
grenade_ammo_take_sound()
end
if obj:section() == "ammo_m209" then
grenade_ammo_take_sound()
end
if obj:section() == "ammo_vog-25" then
grenade_ammo_take_sound()
end
if obj:section() == "ammo_vog-25p" then
grenade_ammo_take_sound()
end
if obj:section() == "ammo_12x70_buck" then
shotgun_ammo_take_sound()
end
if obj:section() == "ammo_12x76_dart" then
shotgun_ammo_take_sound()
end
if obj:section() == "ammo_12x76_zhekan" then
shotgun_ammo_take_sound()
end
if obj:section() == "ammo_5.45x39_fmj" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_5.45x39_ap" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_5.7x28_fmj" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_5.7x28_ap" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_5.56x45_ss190" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_5.56x45_ap" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_7.62x54_7h1" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_7.62x54_7h14" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_7.62x54_ap" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_9x39_sp5" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_9x39_pab9" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_9x39_ap" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_7.62x54r" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_minigun" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_gauss" then
rifle_ammo_take_sound()
end
if obj:section() == "ammo_12.7x55_sc130" then
rifle_ammo_take_sound()
end
if obj:section() == "novice_outfit" then
clother_take_sound()
end
if obj:section() == "outfit_novice_m1" then
clother_take_sound()
end
if obj:section() == "bandit_outfit" then
clother_take_sound()
end
if obj:section() == "outfit_bandit_m1" then
clother_take_sound()
end
if obj:section() == "killer_outfit" then
clother_take_sound()
end
if obj:section() == "outfit_killer_m1" then
clother_take_sound()
end
if obj:section() == "ecolog_outfit" then
clother_take_sound()
end
if obj:section() == "protection_outfit" then
clother_take_sound()
end
if obj:section() == "stalker_outfit" then
outfit_take_sound()
end
if obj:section() == "outfit_stalker_m1" then
outfit_take_sound()
end
if obj:section() == "outfit_stalker_m1" then
outfit_take_sound()
end
if obj:section() == "dolg_outfit" then
outfit_take_sound()
end
if obj:section() == "outfit_dolg_m1" then
outfit_take_sound()
end
if obj:section() == "svoboda_light_outfit" then
outfit_take_sound()
end
if obj:section() == "outfit_svoboda_m1" then
outfit_take_sound()
end
if obj:section() == "soldier_outfit" then
outfit_take_sound()
end
if obj:section() == "specops_outfit" then
outfit_take_sound()
end
if obj:section() == "outfit_specnaz_m1" then
outfit_take_sound()
end
if obj:section() == "monolit_outfit" then
outfit_take_sound()
end
if obj:section() == "scientific_outfit" then
armor_take_sound()
end
if obj:section() == "dolg_scientific_outfit" then
armor_take_sound()
end
if obj:section() == "military_outfit" then
armor_take_sound()
end
if obj:section() == "military_stalker_outfit" then
armor_take_sound()
end
if obj:section() == "military_commander_outfit" then
armor_take_sound()
end
if obj:section() == "svoboda_heavy_outfit" then
armor_take_sound()
end
if obj:section() == "exo_outfit" then
armor_take_sound()
end
if obj:section() == "outfit_exo_m1" then
armor_take_sound()
end
if obj:section() == "wpn_binoc" then
binoc_take_sound()
end
if obj:section() == "binocular_a" then
binoc_take_sound()
end
if obj:section() == "fake_wpn_binoc" then
binoc_take_sound()
end
if obj:section() == "wpn_pkm" then
machine_take_sound()
end
if obj:section() == "wpn_minigun" then
machine_take_sound()
end
if obj:section() == "wpn_vssk" then
machine_take_sound()
end
if obj:section() == "wpn_rpg7" then
gun_take_sound()
end
if obj:section() == "wpn_rg-6" then
gun_take_sound()
end
if obj:section() == "wpn_rg6_m1" then
gun_take_sound()
end
if obj:section() == "wpn_igla" then
gun_take_sound()
end
if obj:section() == "bolt" then
bolt_take_sound()
end
if obj:section() == "ammo_bolts" then
bolt_take_sound()
end
if obj:section() == "bread" then
food_take_sound()
end
if obj:section() == "kolbasa" then
food_take_sound()
end
if obj:section() == "conserva" then
food_take_sound()
end
if obj:section() == "bread_a" then
food_take_sound()
end
if obj:section() == "kolbasa_a" then
food_take_sound()
end
if obj:section() == "conserva_a" then
food_take_sound()
end
if obj:section() == "energy_drink" then
drink_take_sound()
end
if obj:section() == "medkit" then
medkit_take_sound()
end
if obj:section() == "medkit_army" then
medkit_take_sound()
end
if obj:section() == "medkit_scientic" then
medkit_take_sound()
end
if obj:section() == "bandage" then
medkit_take_sound()
end
if obj:section() == "antirad" then
medkit_take_sound()
end
if obj:section() == "guitar_a" then
detectors_take_sound()
end
if obj:section() == "harmonica_a" then
detectors_take_sound()
end
if obj:section() == "device_pda" then
detectors_take_sound()
end
if obj:section() == "device_torch" then
detectors_take_sound()
end
if obj:section() == "fake_device_torch" then
detectors_take_sound()
end
if obj:section() == "detector_simple" then
detectors_take_sound()
end
if obj:section() == "detector_advances" then
detectors_take_sound()
end
if obj:section() == "detector_elite" then
detectors_take_sound()
end
if obj:section() == "mutant_flesh_eye" then
detectors_take_sound()
end
if obj:section() == "mutant_boar_leg" then
detectors_take_sound()
end
if obj:section() == "mutant_dog_tail" then
detectors_take_sound()
end
if obj:section() == "mutant_psevdodog_tail" then
detectors_take_sound()
end
if obj:section() == "mutant_krovosos_jaw" then
detectors_take_sound()
end
if obj:section() == "mutant_burer_hand" then
detectors_take_sound()
end
if obj:section() == "mutant_zombie_hand" then
detectors_take_sound()
end
if obj:section() == "mutant_snork_leg" then
detectors_take_sound()
end
if obj:section() == "af_medusa" then
detectors_take_sound()
end
if obj:section() == "af_cristall_flower" then
detectors_take_sound()
end
if obj:section() == "af_night_star" then
detectors_take_sound()
end
if obj:section() == "af_vyvert" then
detectors_take_sound()
end
if obj:section() == "af_gravi" then
detectors_take_sound()
end
if obj:section() == "af_gold_fish" then
detectors_take_sound()
end
if obj:section() == "af_blood" then
detectors_take_sound()
end
if obj:section() == "af_mincer_meat" then
detectors_take_sound()
end
if obj:section() == "af_soul" then
detectors_take_sound()
end
if obj:section() == "af_drops" then
detectors_take_sound()
end
if obj:section() == "af_fireball" then
detectors_take_sound()
end
if obj:section() == "af_cristall" then
detectors_take_sound()
end
if obj:section() == "af_electra_sparkler" then
detectors_take_sound()
end
if obj:section() == "af_electra_flash" then
detectors_take_sound()
end
if obj:section() == "af_electra_moonlight" then
detectors_take_sound()
end
if obj:section() == "af_ameba_slime" then
detectors_take_sound()
end
if obj:section() == "af_ameba_slug" then
detectors_take_sound()
end
if obj:section() == "af_ameba_mica" then
detectors_take_sound()
end
if obj:section() == "af_dummy_dummy" then
detectors_take_sound()
end
if obj:section() == "af_dummy_spring" then
detectors_take_sound()
end
if obj:section() == "af_dummy_battery" then
detectors_take_sound()
end
if obj:section() == "af_dummy_pellicle" then
detectors_take_sound()
end
if obj:section() == "af_dummy_glassbeads" then
detectors_take_sound()
end
if obj:section() == "af_rusty_thorn" then
detectors_take_sound()
end
if obj:section() == "af_rusty_krisstal" then
detectors_take_sound()
end
if obj:section() == "af_rusty_sea-urchin" then
detectors_take_sound()
end
if obj:section() == "af_fuzz_kolobok" then
detectors_take_sound()
end
if obj:section() == "af_blood_tutorial" then
quest_take_sound()
end
if obj:section() == "quest_case_01" then
quest_take_sound()
end
if obj:section() == "dynamite" then
quest_take_sound()
end
if obj:section() == "esc_wounded_flash" then
quest_take_sound()
end
if obj:section() == "gunslinger_flash" then
quest_take_sound()
end
if obj:section() == "quest_case_02" then
quest_take_sound()
end
if obj:section() == "val_key_to_underground" then
quest_take_sound()
end
if obj:section() == "bar_tiran_pda" then
quest_take_sound()
end
if obj:section() == "bar_lucky_pda" then
quest_take_sound()
end
if obj:section() == "bar_ecolog_flash" then
quest_take_sound()
end
if obj:section() == "lab_x16_documents" then
quest_take_sound()
end
if obj:section() == "good_psy_helmet" then
quest_take_sound()
end
if obj:section() == "bad_psy_helmet" then
quest_take_sound()
end
if obj:section() == "kruglov_flash" then
quest_take_sound()
end
if obj:section() == "crazy_flash" then
quest_take_sound()
end
if obj:section() == "mil_svoboda_leader_pda" then
quest_take_sound()
end
if obj:section() == "dar_pass_flash" then
quest_take_sound()
end
if obj:section() == "dar_pass_document" then
quest_take_sound()
end
if obj:section() == "dar_document1" then
quest_take_sound()
end
if obj:section() == "dar_document2" then
quest_take_sound()
end
if obj:section() == "dar_document3" then
quest_take_sound()
end
if obj:section() == "dar_document4" then
quest_take_sound()
end
if obj:section() == "dar_document5" then
quest_take_sound()
end
if obj:section() == "pri_decoder_documents" then
quest_take_sound()
end
if obj:section() == "cit_doctors_key" then
quest_take_sound()
end
if obj:section() == "decoder" then
quest_take_sound()
end
if obj:section() == "explosive_mobiltank" then
detectors_take_sound()
end
if obj:section() == "explosive_barrel" then
gun_take_sound()
end
if obj:section() == "explosive_tank" then
detectors_take_sound()
end
if obj:section() == "explosive_fuelcan" then
gun_take_sound()
end
end

function pistol_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\pistol]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function rifle_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\rifle]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function bottle_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\bottle]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function drink_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\drink]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function knife_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\knife]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function grenade_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\grenade]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function pistol_ammo_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\ammo\pistol]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function shotgun_ammo_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\ammo\shotgun]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function rifle_ammo_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\ammo\rifle]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function grenade_ammo_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\ammo\grenade]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function clother_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\armor\light]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function outfit_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\armor\medium]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function armor_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\armor\heavy]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function gun_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\gun]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function machine_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\machine]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function binoc_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\binoc]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function bolt_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\bolt]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function food_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\others\food]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function medkit_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\others\medkit]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function detectors_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\others\detectors]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end

function quest_take_sound()
local muzlo = xr_sound.get_safe_sound_object([[take_sounds\others\quest]])
muzlo:play_at_pos(db.actor, vector():set(0,0,0), 0, sound_object.s2d)
end