class "opt_amk" (CUIScriptWnd)
function opt_amk:__init() super()
end

function opt_amk:__finalize()
end

function opt_amk:InitControls(x, y, xml, handler)
	self:Init(x, y, 738, 416)
	self:SetAutoDelete(true)
	
	xml:InitFrame("frame", self)

	local radio_eat = xml:InitCheck("tab_gameplay:check_have_eat", self)
	self:Register(radio_eat, "check_have_eat")	
	self.radio_eat = radio_eat
	radio_eat:SetCheck(game_options.HaveEat)

end